# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andy's Blog
email: andyinbox3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Andy Feng is a software analyst/developer based in Toronto, Canada. 
  He has 9+ years experience in software design and development. 
  He specializes in Java/J2EE and .Net solutions, focusing on 
  Spring, Hibernate, JavaFX, ASP.NET MVC, Entity framework, Web services, 
  JQuery, SQL and related technologies.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andyfengc.github.io" # the base hostname & protocol for your site
twitter_username: andyfengc
github_username:  andyfengc

# Build settings
markdown: kramdown
